name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust this to match the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest fastapi httpx pytest-asyncio
        # Ensure you include all necessary packages

    - name: Change to backend directory and run Pytest
      run: |
        cd backend
        pytest Pytest_fastapi.py
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
    - name: Start FastAPI server
      if: success()
      run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      env:
        PORT: 8000
